# Numpy basics

https://wesmckinney.com/book/numpy-basics.html

In [45]:
import numpy as np
from functools import reduce
from random import randint
from pprint import pprint

# Perfs

Numpy array vs Python list for large sequences.

In [5]:
size = 1_000_000
np_arr = np.arange(size)
py_arr = list(range(size))

%timeit np_arr_2 = np_arr * 2
%timeit py_arr_2 = [item * 2 for item in py_arr]

740 µs ± 18.5 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
68.1 ms ± 3.69 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


# Array

In [7]:
floats_list = [6, 7.5, 8, 0, 1]
floats_array = np.array(floats_list)
floats_array.dtype

dtype('float64')

In [16]:
int_array = np.array([[2,5,8,4], [45,9,9,3]])
int_array.dtype

dtype('int64')

In [18]:
f"Dimensions: {int_array.ndim} - Shape: {int_array.shape}"

'Dimensions: 2 - Shape: (2, 4)'

# Numerical operations

Including _broadcasting_.

In [47]:
arr = np.array([list(range(1, 10)), list(range(1, 10))])

arr_add = arr + arr
arr_mult = arr * arr
arr_norm = 1 / arr # this is broadcasting =)

arr_string = arr_norm.astype(np.string_)

arr_rand1 = np.array([randint(0,100) for _ in range(10)])
arr_rand2 = np.array([randint(0,100) for _ in range(10)])

pprint(arr_rand1)
pprint(arr_rand2)

arr_rand1 > arr_rand2

array([40, 61,  7, 62, 64, 23, 68, 96, 81, 40])
array([53, 81, 64, 75, 28, 12, 13, 11, 61, 66])


array([False, False, False, False,  True,  True,  True,  True,  True,
       False])